import { Socket } from 'socket.io-client';

export type AudioState = 'Idle' | 'Connecting' | 'Connected' | 'Muted' | 'Error';
export type MicState = 'Off' | 'On' | 'Muted';

export interface WebRTCCallbacks {
  onAudioStateChange: (state: AudioState) => void;
  onMicStateChange: (state: MicState) => void;
  onError: (errorMessage: string) => void;
}

export class WebRTCClient {
  private pc: RTCPeerConnection | null = null;
  private localStream: MediaStream | null = null;
  private socket: Socket;
  private targetDeviceId: string;
  private callbacks: WebRTCCallbacks;
  private isMuted: boolean = false;

  constructor(socket: Socket, targetDeviceId: string = 'rover-01', callbacks: WebRTCCallbacks) {
    this.socket = socket;
    this.targetDeviceId = targetDeviceId;
    this.callbacks = callbacks;

    this.setupSocketListeners();
  }

  private setupSocketListeners() {
    this.socket.on('webrtc:answer', async (data: { sdp: RTCSessionDescriptionInit }) => {
      try {
        if (this.pc && data.sdp) {
          console.log('[WebRTC] Received answer SDP from Pi');
          await this.pc.setRemoteDescription(new RTCSessionDescription(data.sdp));
          this.callbacks.onAudioStateChange(this.isMuted ? 'Muted' : 'Connected');
        }
      } catch (err: any) {
        console.error('[WebRTC] Error setting remote description:', err);
        this.callbacks.onError('Failed to handle WebRTC answer from Raspberry Pi');
        this.callbacks.onAudioStateChange('Error');
      }
    });

    this.socket.on('webrtc:ice-candidate', async (data: { candidate: RTCIceCandidateInit }) => {
      try {
        if (this.pc && data.candidate) {
          console.log('[WebRTC] Received ICE candidate from remote');
          await this.pc.addIceCandidate(new RTCIceCandidate(data.candidate));
        }
      } catch (err: any) {
        console.error('[WebRTC] Error adding ICE candidate:', err);
      }
    });

    this.socket.on('call:error', (data: { message: string }) => {
      console.error('[WebRTC] Call error received from signaling:', data.message);
      this.callbacks.onError(data.message);
      this.stopTalk();
    });

    this.socket.on('call:ended', () => {
      console.log('[WebRTC] Call ended by remote');
      this.stopTalk();
    });
  }

  async startTalk(): Promise<void> {
    try {
      this.callbacks.onAudioStateChange('Connecting');

      // 1. Request microphone access
      this.localStream = await navigator.mediaDevices.getUserMedia({
        audio: {
          echoCancellation: true,
          noiseSuppression: true,
          autoGainControl: true,
        },
        video: false,
      });

      this.callbacks.onMicStateChange('On');
      this.isMuted = false;

      // 2. Create RTCPeerConnection
      const rtcConfig: RTCConfiguration = {
        iceServers: [
          { urls: process.env.NEXT_PUBLIC_STUN_SERVER || 'stun:stun.l.google.com:19302' },
        ],
      };

      this.pc = new RTCPeerConnection(rtcConfig);

      // Handle connection state changes
      this.pc.onconnectionstatechange = () => {
        if (!this.pc) return;
        console.log('[WebRTC] Connection state changed:', this.pc.connectionState);
        if (this.pc.connectionState === 'connected') {
          this.callbacks.onAudioStateChange(this.isMuted ? 'Muted' : 'Connected');
        } else if (this.pc.connectionState === 'failed' || this.pc.connectionState === 'disconnected') {
          this.callbacks.onAudioStateChange('Error');
          this.callbacks.onError('WebRTC connection failed or disconnected');
        }
      };

      // Handle ICE candidates generated by local browser
      this.pc.onicecandidate = (event) => {
        if (event.candidate) {
          this.socket.emit('webrtc:ice-candidate', {
            targetDeviceId: this.targetDeviceId,
            candidate: event.candidate,
          });
        }
      };

      // 3. Add audio tracks to PeerConnection
      this.localStream.getAudioTracks().forEach((track) => {
        if (this.pc && this.localStream) {
          this.pc.addTrack(track, this.localStream);
        }
      });

      // 4. Create WebRTC offer
      const offer = await this.pc.createOffer({
        offerToReceiveAudio: false,
        offerToReceiveVideo: false,
      });

      await this.pc.setLocalDescription(offer);

      // 5. Send call:start and offer through Socket.IO signaling
      this.socket.emit('call:start', { targetDeviceId: this.targetDeviceId });
      this.socket.emit('webrtc:offer', {
        targetDeviceId: this.targetDeviceId,
        sdp: offer,
      });

      console.log('[WebRTC] Offer sent to target:', this.targetDeviceId);
    } catch (err: any) {
      console.error('[WebRTC] Error starting talk:', err);
      const msg = err.name === 'NotAllowedError'
        ? 'Microphone permission denied'
        : (err.message || 'Failed to initialize microphone / WebRTC');
      this.callbacks.onError(msg);
      this.stopTalk();
    }
  }

  toggleMute(): void {
    if (!this.localStream) return;

    this.isMuted = !this.isMuted;
    this.localStream.getAudioTracks().forEach((track) => {
      track.enabled = !this.isMuted;
    });

    if (this.isMuted) {
      this.callbacks.onMicStateChange('Muted');
      if (this.pc && this.pc.connectionState === 'connected') {
        this.callbacks.onAudioStateChange('Muted');
      }
    } else {
      this.callbacks.onMicStateChange('On');
      if (this.pc && this.pc.connectionState === 'connected') {
        this.callbacks.onAudioStateChange('Connected');
      }
    }
  }

  stopTalk(): void {
    console.log('[WebRTC] Stopping talk and cleaning up');

    // Notify remote via socket
    if (this.socket && this.socket.connected) {
      this.socket.emit('call:end', { targetDeviceId: this.targetDeviceId });
    }

    // Stop local media tracks
    if (this.localStream) {
      this.localStream.getTracks().forEach((track) => track.stop());
      this.localStream = null;
    }

    // Close PeerConnection
    if (this.pc) {
      this.pc.close();
      this.pc = null;
    }

    this.isMuted = false;
    this.callbacks.onMicStateChange('Off');
    this.callbacks.onAudioStateChange('Idle');
  }

  destroy() {
    this.stopTalk();
    this.socket.off('webrtc:answer');
    this.socket.off('webrtc:ice-candidate');
    this.socket.off('call:error');
    this.socket.off('call:ended');
  }
}
